### ISSUE TITLE
SemiBold static weight?

### ISSUE THREAD

**Issue by cssobral2013** [tokotype/PlusJakartaSans#16]
This is because, the SemiBold weight is implicit by source and variable font, but not implemented.

**Comment by tokotype** [comment]
We're aware of this situation, and the coming update will be added SemiBold to the family

**Comment by amoghsrivastava** [comment]
@tokotype any updates on when the semibold is coming out? Waiting to use it on my project!

**Comment by cssobral2013** [comment]
Closing, because version 2.6 has SemiBold weight.
