### ISSUE TITLE
[Suggestion] 9 weights (both Display and Text)

### ISSUE THREAD

**Issue by cssobral2013** [tokotype/PlusJakartaSans#2]
Note: This is superseding #1.

**Comment by cssobral2013** [comment]
Note 2: as @tokotype explained in #1, the font is expected to receive a variable version, so I closed it and opened this new issue which will be more abrangent.

**Comment by cssobral2013** [comment]
This issue will be closed 'cause versions 2.4 onwards have now 7 weights + variable, what will be enough.

**Comment by mrleblanc101** [comment]
It would be nice to have all weight for people that do not use variable font.
