### ISSUE TITLE
"x" after a number is not rendering properly. 

### ISSUE THREAD

**Issue by akhilpokle** [tokotype/PlusJakartaSans#23]
![image](https://user-images.githubusercontent.com/17247801/148024165-3babc6b1-3951-4ec8-8209-bf5252523e3d.png)

**Comment by emilevictorportenart** [comment]
It's probably based on your ligature option. When deactivating contextual ligatures, it's working as expected.

![CleanShot 2022-01-05 at 10 46 18](https://user-images.githubusercontent.com/921074/148196743-389e55d4-94d3-4033-b25a-1ee500c98e00.png)
