### ISSUE TITLE
The letters F and I have problems when they become words

### ISSUE THREAD

**Issue by fiik346** [tokotype/PlusJakartaSans#27]
![Screenshot_2022-04-20-09-45-03-678_com kiwibrowser browser](https://user-images.githubusercontent.com/48739090/164140766-32c08a0e-76ca-4b87-a7d0-e07ed463b3a1.jpg)
Is this a built-in design or a bug when f and I become one?

**Comment by emilevictorportenart** [comment]
It's a feature, it's called ligature. You can decide to disabled it in your css like this

```* {
  font-variant-ligatures: none;
}```
