### ISSUE TITLE
Request for Lithuanian language support

### ISSUE THREAD

**Issue by donatasben** [tokotype/PlusJakartaSans#3]
Hi. Love your font! It would be my endgame font, however it is missing my native language characters. Do you plan on expanding character set? It would be a game changer to include characters like "ĄČĘĖĮŠŲŪŽ" from Lithuanian language! (Š & Ž already exist)

![lithuanian characters](https://user-images.githubusercontent.com/4421344/88116893-5e098e80-cbc2-11ea-8c70-d4ec691e78dd.png)

Amazing font, none the less!
Keep up the good work!

**Comment by tokotype** [comment]
Hi, sure thing!
We're planning to add more European accents in the next update. Thanks for asking
