### ISSUE TITLE
Remove tail from letter "æ"

### ISSUE THREAD

**Issue by wpbft** [tokotype/PlusJakartaSans#31]
Please remove the tail (middle bar) from Scandinavian letter "æ" to follow common practice and improve readability. Quick edit attached to illustrate. Thanks for the great work you've put into this font.

![scandinavian_letter](https://user-images.githubusercontent.com/70260054/195530134-1fd9ac81-1963-49cd-b407-6bb423a93c90.jpg)

**Comment by tokotype** [comment]
thanks for the feedback, this will updated in the new development
