### ISSUE TITLE
v2.7 (2.007) release - no kerning in static fonts

### ISSUE THREAD

**Issue by kenmcd** [tokotype/PlusJakartaSans#34]
In the v2.7 (2.007) fonts released today (2023-05-19) it appears that the static fonts have no kerning feature.
The variable fonts do have kerning, so it appears to affect only the static fonts.

**Comment by tokotype** [comment]
We are aware of this issue, will fixed in the next update. Thanks for noticing us

**Comment by kenmcd** [comment]
Fixed in v2.7.1 (2.071) release (2023-05-25).
