### ISSUE TITLE
Provide woff and woff2 formats

### ISSUE THREAD

**Issue by raunaqgupta** [tokotype/PlusJakartaSans#6]
It would be nice to also provide `woff` and `woff2` formats as part of the releases. They are usually structured under a folder titled: `webfonts` like in the case here: https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

A potential way to atleast provide woff2 format would be to use some kind of github action that utilizes this library: https://github.com/google/woff2

**Comment by tokotype** [comment]
Currently the webfonts package has been added in the newest version (v.2.4) in this repository.

**Comment by mrleblanc101** [comment]
It would be nice to provide a css file with the @font-face declaration.
Is Light `font-weight: 200`, or `font-weight: 300`,
Is ExtraBold `font-weight: 800` or `font-weight: 900`, etc

**Comment by voicecode-bv** [comment]
For future references, I am using this as a guideline:

[Common weight name mapping](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#common_weight_name_mapping)

`
@font-face {
    font-family: 'PlusJakartaSans-Light';
    src: url(/fonts/PlusJakartaSans-Regular.woff2) format('woff2'),
        url(/fonts/PlusJakartaSans-Regular.woff) format('woff'),
        url(/fonts/PlusJakartaSans-Regular.ttf) format('truetype');
    font-weight: 300;
    font-display: swap;
    font-style: normal;
}

@font-face {
    font-family: 'PlusJakartaSans-Regular';
    src: url(/fonts/PlusJakartaSans-Regular.woff2) format('woff2'),
        url(/fonts/PlusJakartaSans-Regular.woff) format('woff'),
        url(/fonts/PlusJakartaSans-Regular.ttf) format('truetype');
    font-weight: 400;
    font-display: swap;
    font-style: normal;
}

@font-face {
    font-family: 'PlusJakartaSans-Medium';
    src: url(/fonts/PlusJakartaSans-Medium.woff2) format('woff2'),
        url(/fonts/PlusJakartaSans-Medium.woff) format('woff'),
        url(/fonts/PlusJakartaSans-Medium.ttf) format('truetype');
    font-weight: 500;
    font-display: swap;
    font-style: normal;
}

@font-face {
    font-family: 'PlusJakartaSans-Bold';
    src: url(/fonts/PlusJakartaSans-Bold.woff2) format('woff2'),
        url(/fonts/PlusJakartaSans-Bold.woff) format('woff'),
        url(/fonts/PlusJakartaSans-Bold.ttf) format('truetype');
    font-weight: 700;
    font-display: swap;
    font-style: normal;
}

@font-face {
    font-family: 'PlusJakartaSans-ExtraBold';
    src: url(/fonts/PlusJakartaSans-ExtraBold.woff2) format('woff2'),
        url(/fonts/PlusJakartaSans-ExtraBold.woff) format('woff'),
        url(/fonts/PlusJakartaSans-ExtraBold.ttf) format('truetype');
    font-weight: 800;
    font-display: swap;
    font-style: normal;
}
`
