### ISSUE TITLE
‘Backward’ Apostrophes

### ISSUE THREAD

**Issue by yuyanglu** [tokotype/PlusJakartaSans#7]
<img width="412" alt="Screen Shot 2020-12-11 at 02 55 47" src="https://user-images.githubusercontent.com/10539965/101895466-6c9a1780-3b5c-11eb-8c45-07d83c1a3a41.png">

As shown in the image, apostrophes seem to behave incorrectly(facing the wrong way). Is this a bug?

**Comment by tokotype** [comment]
Thank you for noticing! We already fixed the source file, that was reversed glyph name between `quoteleft` and `quoteright`
We will delivered the fixed files in the next package release.
